#!/bin/bash


if [ "$1" = "get" ]; then
    MAX_BRIGHTNESS=$(brightnessctl -n | awk -F'\n|:' 'NR==3{print $2}')
    CUR_BRIGHTNESS=$(brightnessctl g)
    echo "${CUR_BRIGHTNESS} *100 / ${MAX_BRIGHTNESS}" | bc
elif [ "$1" = "set" ]; then
    brightnessctl s "${2}%"
fi
