#!/bin/bash 

if [ "$1" = "get" ]; then 
    wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk -F">>|:" '{print $2}' | sed '/\[MUTED\]/s/\[MUTED\]/*100/; t; s/$/ *100/' | bc
elif [ "$1" = "set" ]; then 
    wpctl set-volume @DEFAULT_AUDIO_SINK@ "${2}%"
elif [ "$1" = "mute" ]; then
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
fi

