# fonts

font_family Ubuntu Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 16 


# cursor
cursor_blink_interval 0.5
scrollback_lines 2000
detect_urls yes
open_url_with default
open_url_modifiers ctrl


# color scheme
# (Gruvbox) 
#  background #1d2021
#  foreground #ebdbb2

# (Dracula)
#  background #282a36
#  foreground #f8f8f2
#  selection_foreground #44475a

# (Gray)
#  foreground #FFFFFF
#  background #1e1f21
#  selection_foreground #5c5959



# (Custom dark test)
foreground #FFFFFF
background #010203 
selection_foreground #5c5959



enable_audio_bell no

window_border_width 2pt
window_margin_width 1.8
window_padding_width 1.5
