#!/bin/bash

BAT=/sys/class/power_supply/BAT0
ADP=/sys/class/power_supply/AC

bat_level=$(cat "$BAT/energy_now")
bat_max=$(cat "$BAT/energy_full")

bat_percent=$(("bat_level*100/bat_max"))
charging=$(cat "$ADP/online")

if [ "$bat_percent" -lt 20 -a "$charging" -eq 0 ]; then
    dunstify "Low battery"
fi
