theme:
  active: Blue
  banner: Cyan
  error_border: Red
  error_text: LightRed
  hint: Red 
  hovered: LightBlue
  inactive: Blue
  playbar_background: Black
  playbar_progress: Red
  playbar_progress_text: White
  playbar_text: White
  selected: Cyan
  text: White
  header: White
